### ISSUE TITLE
Berry Website ( I need guidance! )

### ISSUE THREAD

**Issue by MatthewDesmarais** [MatthewDesmarais/navigation-highlight#1]
Im having a ton of trouble setting up the css to make it look the way yours does.
Any advice to help me get over this bump with my navigation?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Let’s start with some HTML changes:

The `<a>` tags aren’t closed here:
https://github.com/MatthewDesmarais/navigation-highlight/blob/gh-pages/index.html#L16-L19
The `/` is on the wrong side, should be: `</a>`

--- 

- https://github.com/MatthewDesmarais/navigation-highlight/blob/gh-pages/index.html#L13
- https://github.com/MatthewDesmarais/navigation-highlight/blob/gh-pages/index.html#L13

The paragraph & "Berries, berries oh my" should be inside a `<main>` tag. At the top of the page it says only "Berries".
